AvisFormationWebAspNetCore/Controllers/ContactController.cs
using AvisFormationWebAspNetCore.Models;
using Data;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AvisFormationWebAspNetCore.Controllers
{
    public class ContactController : Controller
    {
        IContactRepository _context;
        public ContactController (IContactRepository context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var vm = new EnvoiEmailViewModel();
            return View(vm);
        }


        public IActionResult SaveMessage(EnvoiEmailViewModel viewModel)
        {
            if(!ModelState.IsValid)
            {
                return View("Index", viewModel);
            }

            _context.SaveMessage(viewModel.Nom, viewModel.Email, viewModel.Message);

            return View();
        }
    }
}

AvisFormationWebAspNetCore/Controllers/FormationController.cs
using AvisFormationWebAspNetCore.Models;
using Data;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AvisFormationWebAspNetCore.Controllers
{
    public class FormationController : Controller
    {
        IFormationRepository _repository;
        public FormationController(IFormationRepository repository)
        {
            _repository = repository;
        }

        public IActionResult Index()
        {
            var vm = new ToutesLesFormationViewModel();
            vm.Message = "Ceci est un message du controlleur";
            vm.Nombre = 93;

            // pas oublié de bien le mettre dans le return sinon message d'ereur
            // attention jamais mettre de double (pb avec la virgule) mettre des string
            return View(vm);
        }

        public IActionResult ToutesLesFormations()
        {
            //FormationMemoryRepository repository = new FormationMemoryRepository();
            var listFormations = _repository.GetAllFormations();
            var vm = new List<DetailFormationViewModel>();
            foreach (var formation in listFormations)
            {
                var temp = new DetailFormationViewModel();
                temp.Formation = formation;
                if (formation.Avis != null && formation.Avis.Count >0)
                {
                    temp.NoteMoyenne = Math.Round(formation.Avis.Select(a=>a.Note).ToList().Average(),1);
                }
                vm.Add(temp);
            }
            return View(vm);
        }

        public IActionResult DetailsFormation(string nomSeo)
        {
            var formation = _repository.GetFormationByNomSeo(nomSeo);
            if (formation == null)
            {
                return RedirectToAction("ToutesLesFormations");
            }
            var vm = new DetailFormationViewModel();
            vm.Formation = formation;
            if (formation.Avis != null && formation.Avis.Count >0)
            {
                vm.NoteMoyenne = Math.Round(formation.Avis.Select(a=>a.Note).ToList().Average(),1);
            }

            return View(vm);
        }






    }

}

AvisFormationWebAspNetCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AvisFormations</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
    <link rel="stylesheet" href="~/css/site.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Avis Formations</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Formation" asp-action="ToutesLesFormations">Formations</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Contact" asp-action="Index">Contact</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-dark text-light">
        <div class="container text-center">
            &copy; 2021 - AvisFormations
        </div>
    </footer>


    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>

    <environment exclude="Development">
        <script src="~/js/bundle.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>