AvisFormationWebAspNetCore/Models/ToutesLesFormationViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AvisFormationWebAspNetCore.Models
{
    public class ToutesLesFormationViewModel
    {
        public string Message { get; set; }
        public int Nombre { get; set; }

    }
}

AvisFormationWebAspNetCore/Controllers/AvisController.cs
using System;
using AvisFormationWebAspNetCore.Models;
using Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AvisFormationWebAspNetCore.Controllers
{
    public class AvisController : Controller
    {
        IFormationRepository _repository;
        IAvisRepository _avisRepository;
        UserManager<IdentityUser> _userManager;
        public AvisController(IFormationRepository repository,
            IAvisRepository avisRepository, UserManager<IdentityUser> userManager)
        {
            _repository = repository;
            _avisRepository = avisRepository;
            _userManager = userManager;      
        }

        [Authorize]
        public IActionResult LaisserUnAvis(string idFormation)
        {
            int iIdFormation = -1;
            if (!Int32.TryParse(idFormation, out iIdFormation))
            {
                return RedirectToAction("ToutesLesFormations", "Formation");
            }
            //FormationMemoryRepository repository = new FormationMemoryRepository();
            var formation = _repository.GetFormationById(iIdFormation);
            if (formation == null)
            {
                return RedirectToAction("ToutesLesFormations", "Formation");
            }

            var vm = new LaisserUnAvisViewModel();
            vm.NomFormation = formation.Nom;
            vm.IdFormation = formation.Id.ToString();

            return View(vm);
        }

        [Authorize]
        public IActionResult SaveComment(LaisserUnAvisViewModel viewModel)
        {
            if(!ModelState.IsValid)
            {
                return View("LaisserUnAvis", viewModel);
            }
                   

            if(String.IsNullOrEmpty(viewModel.Note))
            {
                return RedirectToAction("LaisserUnAvis", new { idFormation = viewModel.IdFormation });
            }

            var currentUser = this.User;
            var userName = _userManager.GetUserName(currentUser);

            //AvisRepository repository = new AvisRepository();
            _avisRepository.SaveAvis(viewModel.Commentaire,
                userName, viewModel.IdFormation, viewModel.Note);
           
            return RedirectToAction("DetailsFormation", "Formation", new { idFormation = viewModel.IdFormation });
        }

    }
}

AvisFormationWebAspNetCore/Controllers/FormationController.cs
using AvisFormationWebAspNetCore.Models;
using Data;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AvisFormationWebAspNetCore.Controllers
{
    public class FormationController : Controller
    {
        IFormationRepository _repository;
        public FormationController(IFormationRepository repository)
        {
            _repository = repository;
        }

        public IActionResult Index()
        {
            var vm = new ToutesLesFormationViewModel();
            vm.Message = "Ceci est un message du controlleur";
            vm.Nombre = 93;

            // pas oublié de bien le mettre dans le return sinon message d'ereur
            // attention jamais mettre de double (pb avec la virgule) mettre des string
            return View(vm);
        }

        public IActionResult ToutesLesFormations()
        {
            //FormationMemoryRepository repository = new FormationMemoryRepository();
            var listFormations = _repository.GetAllFormations();
            var vm = new List<DetailFormationViewModel>();
            foreach (var formation in listFormations)
            {
                var temp = new DetailFormationViewModel();
                temp.Formation = formation;
                if (formation.Avis != null && formation.Avis.Count >0)
                {
                    temp.NoteMoyenne = Math.Round(formation.Avis.Select(a=>a.Note).ToList().Average(),1);
                }
                vm.Add(temp);
            }
            return View(vm);
        }

        public IActionResult DetailsFormation(string nomSeo)
        {
            var formation = _repository.GetFormationByNomSeo(nomSeo);
            if (formation == null)
            {
                return RedirectToAction("ToutesLesFormations");
            }
            var vm = new DetailFormationViewModel();
            vm.Formation = formation;
            if (formation.Avis != null && formation.Avis.Count >0)
            {
                vm.NoteMoyenne = Math.Round(formation.Avis.Select(a=>a.Note).ToList().Average(),1);
            }

            return View(vm);
        }






    }

}

AvisFormationWebAspNetCore/Views/Formation/DetailsFormation.cshtml
@model DetailFormationViewModel
@{
    ViewData["Title"] = Model.Formation.Nom;
}

<h1>@Model.Formation.Nom</h1>

<p><b>@Model.Formation.Description</b></p>

<div>
    La formation est notée @Model.NoteMoyenne/5
    @for (int i = 1; i <= Model.NoteMoyenne; i++)
    {
        <span class="fa fa-star orange"></span>
    }
</div>
<a asp-action="LaisserUnAvis"
   asp-controller="Avis"
   asp-route-idFormation="@Model.Formation.Id">Laissez un avis sur la formation</a>

<p>Voici ce qu'en disent les anciens élèves :</p>
@foreach (var avis in Model.Formation.Avis)
{
    <div class="avis-block">
        <div>
            @avis.Note/5
            @for (int i = 1; i <= avis.Note; i++)
            {
                <span class="fa fa-star orange"></span>
            }
            @if (!((avis.Note % 1) == 0))
            {<span class="fa fa-star-half orange"></span>}
        </div>
        <div><i>@avis.NomUtilisateur</i></div>
        <div>@avis.Commentaire</div>
    </div>
}

AvisFormationWebAspNetCore/Views/Formation/Index.cshtml
@model ToutesLesFormationViewModel
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>
<p>Ceci est une vue</p>
<p>@Model.Message</p>
<p>Ceci est la valeur passée : @Model.Nombre</p>

AvisFormationWebAspNetCore/Views/Formation/ToutesLesFormations.cshtml
@model List<DetailFormationViewModel>
@{
    ViewData["Title"] = "Toutes les formations";
}

<h1>Toutes nos formations</h1>

<div class="row text-center justify-content-md-center">

    @foreach (var formation in Model)
    {
    <div class="formation-block col-md-6 col-lg-4">
        <a asp-controller="Formation"
           asp-action="DetailsFormation"
           asp-route-nomSeo="@formation.Formation.NomSeo">@formation.Formation.Nom</a>

        @*<div>
            @formation.NoteMoyenne/5
            @for (int i = 1; i <= formation.NoteMoyenne; i++)
            {
                <span class="fa fa-star orange"></span>
            }
            @if (!((formation.NoteMoyenne % 1) == 0))
            {
                <span class="fa fa-star-half orange"></span>
            }
        </div>*@

        <p>@formation.Formation.Description</p>

        <!-- faire le truc des moyennes-->

    </div>
    }
</div>